name: farmwise_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0
  http: ^1.3.0
  intl: ^0.20.2
  url_launcher: ^6.1.11
  image_picker: ^1.1.2
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_messaging: ^15.2.5
  geolocator: 13.0.4
  map_location_picker: ^1.2.7
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.7
  markdown_widget: ^2.3.2+8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/farmwise-icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
