// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoMtu2H3aqxEJftP0zN8vEKgZGtjPuAt8',
    appId: '1:771199074866:web:8c940f76e140dacf4e322b',
    messagingSenderId: '771199074866',
    projectId: 'farmwise-458102',
    authDomain: 'farmwise-458102.firebaseapp.com',
    storageBucket: 'farmwise-458102.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW5w1y1Yu_Zz1jDz4xLHzlw3nf3ltklaE',
    appId: '1:771199074866:android:43c40502a0b104074e322b',
    messagingSenderId: '771199074866',
    projectId: 'farmwise-458102',
    storageBucket: 'farmwise-458102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNINVJDCsC3XSG41NGaGxE_wuxwbdyDZM',
    appId: '1:771199074866:ios:010c5ad2b09495de4e322b',
    messagingSenderId: '771199074866',
    projectId: 'farmwise-458102',
    storageBucket: 'farmwise-458102.firebasestorage.app',
    iosBundleId: 'com.example.farmwiseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNINVJDCsC3XSG41NGaGxE_wuxwbdyDZM',
    appId: '1:771199074866:ios:010c5ad2b09495de4e322b',
    messagingSenderId: '771199074866',
    projectId: 'farmwise-458102',
    storageBucket: 'farmwise-458102.firebasestorage.app',
    iosBundleId: 'com.example.farmwiseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoMtu2H3aqxEJftP0zN8vEKgZGtjPuAt8',
    appId: '1:771199074866:web:afaded6de0d043fe4e322b',
    messagingSenderId: '771199074866',
    projectId: 'farmwise-458102',
    authDomain: 'farmwise-458102.firebaseapp.com',
    storageBucket: 'farmwise-458102.firebasestorage.app',
  );
}
